package com.timexautoweb.domain;
// Generated Feb 13, 2013 6:38:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer id;
	private String name;
	private String state;
	private Set timesheets = new HashSet(0);

	public Department() {
	}

	public Department(String name, String state) {
		this.name = name;
		this.state = state;
	}

	public Department(String name, String state, Set timesheets) {
		this.name = name;
		this.state = state;
		this.timesheets = timesheets;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Set getTimesheets() {
		return this.timesheets;
	}

	public void setTimesheets(Set timesheets) {
		this.timesheets = timesheets;
	}

}
