package com.timexautoweb.domain;
// Generated Feb 13, 2013 6:38:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private Integer id;
	private Timesheet timesheet;
	private double regularRate;
	private double overtimeRate;
	private double taxPercent;
	private double netPay;

	public Payment() {
	}

	public Payment(Timesheet timesheet, double regularRate, double overtimeRate, double taxPercent, double netPay) {
		this.timesheet = timesheet;
		this.regularRate = regularRate;
		this.overtimeRate = overtimeRate;
		this.taxPercent = taxPercent;
		this.netPay = netPay;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Timesheet getTimesheet() {
		return this.timesheet;
	}

	public void setTimesheet(Timesheet timesheet) {
		this.timesheet = timesheet;
	}

	public double getRegularRate() {
		return this.regularRate;
	}

	public void setRegularRate(double regularRate) {
		this.regularRate = regularRate;
	}

	public double getOvertimeRate() {
		return this.overtimeRate;
	}

	public void setOvertimeRate(double overtimeRate) {
		this.overtimeRate = overtimeRate;
	}

	public double getTaxPercent() {
		return this.taxPercent;
	}

	public void setTaxPercent(double taxPercent) {
		this.taxPercent = taxPercent;
	}

	public double getNetPay() {
		return this.netPay;
	}

	public void setNetPay(double netPay) {
		this.netPay = netPay;
	}

}
